In [ ]:
import pandas as pd
df = pd.read_csv('demo.csv')
df

,Emp ID,Name Prefix,First Name,Middle Initial,Last Name,Gender,E Mail,Father's Name,Mother's Name,Mother's Maiden Name,...,SSN,Phone No.,Place Name,County,City,State,Zip,Region,User Name,Password
0,850297,Ms.,Shawna,W,Buck,F,shawna.buck@gmail.com,Rosario Buck,Keisha Buck,Hendricks,...,222-11-7603,702-771-7149,Las Vegas,Clark,Las Vegas,NV,89128,West,swbuck,ja8?k3BTF^]o@<&
1,304721,Mr.,Nathaniel,Z,Burke,M,nathaniel.burke@walmart.com,Derrick Burke,Phoebe Burke,Pugh,...,550-99-9897,231-765-6923,Irons,Lake,Irons,MI,49644,Midwest,nzburke,tPA@4Wh9Ja$+Ln
2,412317,Drs.,Elisabeth,W,Foster,F,elisabeth.foster@gmail.com,Irwin Foster,Janie Foster,Delaney,...,215-91-0004,270-749-4774,Lexington,Fayette,Lexington,KY,40501,South,ewfoster,5D.B4IGNkWJfG<~
3,621375,Mrs.,Briana,C,Lancaster,F,briana.lancaster@yahoo.com,Jeffrey Lancaster,Shelby Lancaster,Weiss,...,534-71-1053,219-623-8216,Munster,Lake,Munster,IN,46321,Midwest,bclancaster,I%?JDM;pW
4,787549,Hon.,Estella,L,Potter,F,estella.potter@gmail.com,Booker Potter,Katelyn Potter,Pate,...,644-29-6396,907-677-8486,Fairbanks,Fairbanks North Star,Fairbanks,AK,99709,West,elpotter,j4jkEXfC&Rh
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,568435,Ms.,Bonnie,K,Baker,F,bonnie.baker@bp.com,Edwardo Baker,Pauline Baker,Robinson,...,064-02-6162,262-696-9171,Mukwonago,Waukesha,Mukwonago,WI,53149,Midwest,bkbaker,a?Co:/r;nu_wTQ
996,597409,Mr.,Luke,S,Turner,M,luke.turner@charter.net,Javier Turner,Nicole Turner,Sykes,...,056-02-8240,231-629-0498,Freeport,Barry,Freeport,MI,49325,Midwest,lsturner,7n5@64VC7|
997,359608,Hon.,Eva,S,Holman,F,eva.holman@hotmail.com,Coy Holman,Haley Holman,Boyle,...,343-11-1935,209-912-6705,Turlock,Stanislaus,Turlock,CA,95381,West,esholman,DG<<<e}*WgD<U
998,803426,Mrs.,Maritza,H,Christian,F,maritza.christian@microsoft.com,Dion Christian,Stephanie Christian,Mooney,...,336-11-5030,203-224-9056,Stamford,Fairfield,Stamford,CT,6910,Northeast,mhchristian,Krs@#TnM
999,669618,Drs.,Phyllis,H,Dudley,F,phyllis.dudley@yahoo.co.in,Jarrod Dudley,Latisha Dudley,Wilcox,...,101-02-6501,405-970-2341,Meno,Major,Meno,OK,73760,South,phdudley,h6wt@400%&Uu

Warning: Total number of columns (37) exceeds max_columns (20) limiting to first (20) columns.

1. Which month saw the highest joining of the employees

function name: max_joinings_month()

inputs: DataFrame

outputs: str

In [ ]:
def max_joinings_month(df):
  return df.max('Month Name of Joining')
print("on demo.csv",max_joinings_month(df))
# print("on test.csv",max_joinings_month(test_df))

ValueError: ignored